package io.nepalpay.core.connectips.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Signed form payload for ConnectIPS payment initiation.
 *
 * <p>ConnectIPS uses a form-submission model similar to eSewa.
 * Your backend generates this signed payload and the frontend
 * POSTs it to the ConnectIPS gateway URL.
 *
 * <p>IMPORTANT: ConnectIPS uses RSA-SHA256 digital signatures
 * generated from a .pfx certificate file issued by NCHL.
 * You must register as a merchant with NCHL to obtain credentials.
 * Contact: connectips@nchl.com.np
 *
 * <p>UAT (sandbox) gateway URL:
 * https://uat.connectips.com/connectipswebgw/loginpage
 *
 * <p>Production gateway URL:
 * https://connectips.com/connectipswebgw/loginpage
 *
 * @param merchantId     Your NCHL-assigned merchant ID
 * @param appId          Your application ID from NCHL
 * @param appName        Your application name from NCHL
 * @param txnId          Your unique transaction ID
 * @param txnDate        Transaction date (DD-MM-YYYY)
 * @param txnCrncy       Currency code (always NPR)
 * @param txnAmt         Transaction amount in paisa
 * @param referenceId    Your order/reference ID
 * @param remarks        Optional remarks shown to user
 * @param particulars    Optional particulars
 * @param token          RSA-SHA256 signed token (generated by ConnectIpsClient)
 * @param formActionUrl  The ConnectIPS gateway URL to POST to
 */
public record ConnectIpsFormPayload(

        @JsonProperty("MERCHANTID")
        int merchantId,

        @JsonProperty("APPID")
        String appId,

        @JsonProperty("APPNAME")
        String appName,

        @JsonProperty("TXNID")
        String txnId,

        @JsonProperty("TXNDATE")
        String txnDate,

        @JsonProperty("TXNCRNCY")
        String txnCrncy,

        @JsonProperty("TXNAMT")
        long txnAmt,

        @JsonProperty("REFERENCEID")
        String referenceId,

        @JsonProperty("REMARKS")
        String remarks,

        @JsonProperty("PARTICULARS")
        String particulars,

        @JsonProperty("TOKEN")
        String token,

        @JsonProperty("form_action_url")
        String formActionUrl

) {}