package io.nepalpay.core.esewa.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Signed form payload your backend returns to the frontend.
 *
 * eSewa uses a FORM-SUBMISSION model — unlike Khalti which is API-first.
 * Your backend generates this signed payload, returns it to the frontend,
 * and the frontend POSTs it directly to eSewa's form URL.
 *
 * Flow:
 * <pre>
 * 1. Frontend calls your backend: POST /api/payment/esewa/initiate
 * 2. Your backend calls: esewaClient.buildFormPayload(...)
 * 3. Your backend returns this EsewaFormPayload to the frontend
 * 4. Frontend renders a form with these fields and POSTs to formActionUrl
 * 5. eSewa handles payment and redirects to your successUrl
 * 6. Your backend receives callback, calls: esewaClient.verifyCallback(data)
 * </pre>
 *
 * @param amount                 Base amount (NPR)
 * @param taxAmount              Tax amount (0 if none)
 * @param totalAmount            amount + taxAmount + charges
 * @param transactionUuid        Your unique transaction ID (store in DB!)
 * @param productCode            Your eSewa merchant/product code
 * @param productServiceCharge   Service charge (0 if none)
 * @param productDeliveryCharge  Delivery charge (0 if none)
 * @param successUrl             Where eSewa redirects on success
 * @param failureUrl             Where eSewa redirects on failure
 * @param signedFieldNames       Always: "total_amount,transaction_uuid,product_code"
 * @param signature              HMAC-SHA256 signature (generated by EsewaClient)
 * @param formActionUrl          The eSewa form URL to POST to (sandbox or production)
 */
public record EsewaFormPayload(

        @JsonProperty("amount")
        String amount,

        @JsonProperty("tax_amount")
        String taxAmount,

        @JsonProperty("total_amount")
        String totalAmount,

        @JsonProperty("transaction_uuid")
        String transactionUuid,

        @JsonProperty("product_code")
        String productCode,

        @JsonProperty("product_service_charge")
        String productServiceCharge,

        @JsonProperty("product_delivery_charge")
        String productDeliveryCharge,

        @JsonProperty("success_url")
        String successUrl,

        @JsonProperty("failure_url")
        String failureUrl,

        @JsonProperty("signed_field_names")
        String signedFieldNames,

        @JsonProperty("signature")
        String signature,

        /**
         * The URL your frontend form must POST to.
         * Sandbox:    https://rc-epay.esewa.com.np/api/epay/main/v2/form
         * Production: https://epay.esewa.com.np/api/epay/main/v2/form
         *
         * Frontend usage (Angular/React/HTML):
         * <form [action]="payload.formActionUrl" method="POST">
         *   <!-- render all other fields as hidden inputs -->
         * </form>
         */
        @JsonProperty("form_action_url")
        String formActionUrl

) {}